// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zapslog/config.proto

package zapslog

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	TimeFormat    string                 `protobuf:"bytes,3,opt,name=time_format,json=timeFormat,proto3" json:"time_format,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Dir           string                 `protobuf:"bytes,5,opt,name=dir,proto3" json:"dir,omitempty"`
	MaxSize       int32                  `protobuf:"varint,6,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	MaxBackups    int32                  `protobuf:"varint,7,opt,name=max_backups,json=maxBackups,proto3" json:"max_backups,omitempty"`
	MaxAge        int32                  `protobuf:"varint,8,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	Compress      bool                   `protobuf:"varint,9,opt,name=compress,proto3" json:"compress,omitempty"`
	File          bool                   `protobuf:"varint,10,opt,name=file,proto3" json:"file,omitempty"`
	ErrorFile     bool                   `protobuf:"varint,11,opt,name=error_file,json=errorFile,proto3" json:"error_file,omitempty"`
	AppName       string                 `protobuf:"bytes,12,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_zapslog_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_zapslog_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_zapslog_config_proto_rawDescGZIP(), []int{0}
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Log) GetTimeFormat() string {
	if x != nil {
		return x.TimeFormat
	}
	return ""
}

func (x *Log) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *Log) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *Log) GetMaxSize() int32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *Log) GetMaxBackups() int32 {
	if x != nil {
		return x.MaxBackups
	}
	return 0
}

func (x *Log) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *Log) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

func (x *Log) GetFile() bool {
	if x != nil {
		return x.File
	}
	return false
}

func (x *Log) GetErrorFile() bool {
	if x != nil {
		return x.ErrorFile
	}
	return false
}

func (x *Log) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

var File_zapslog_config_proto protoreflect.FileDescriptor

const file_zapslog_config_proto_rawDesc = "" +
	"\n" +
	"\x14zapslog/config.proto\x12\azapslog\x1a\x17validate/validate.proto\"\x9a\x03\n" +
	"\x03Log\x127\n" +
	"\x05level\x18\x01 \x01(\tB!\xfaB\x1er\x1cR\x00R\x05debugR\x04infoR\x04warnR\x05errorR\x05level\x12,\n" +
	"\x06format\x18\x02 \x01(\tB\x14\xfaB\x11r\x0fR\aconsoleR\x04jsonR\x06format\x12\x1f\n" +
	"\vtime_format\x18\x03 \x01(\tR\n" +
	"timeFormat\x12\x1f\n" +
	"\x06output\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06output\x12\x10\n" +
	"\x03dir\x18\x05 \x01(\tR\x03dir\x12\"\n" +
	"\bmax_size\x18\x06 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\amaxSize\x12(\n" +
	"\vmax_backups\x18\a \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\n" +
	"maxBackups\x12 \n" +
	"\amax_age\x18\b \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x06maxAge\x12\x1a\n" +
	"\bcompress\x18\t \x01(\bR\bcompress\x12\x12\n" +
	"\x04file\x18\n" +
	" \x01(\bR\x04file\x12\x1d\n" +
	"\n" +
	"error_file\x18\v \x01(\bR\terrorFile\x12\x19\n" +
	"\bapp_name\x18\f \x01(\tR\aappNameB$Z\"yola/test/internal/zapslog;zapslogb\x06proto3"

var (
	file_zapslog_config_proto_rawDescOnce sync.Once
	file_zapslog_config_proto_rawDescData []byte
)

func file_zapslog_config_proto_rawDescGZIP() []byte {
	file_zapslog_config_proto_rawDescOnce.Do(func() {
		file_zapslog_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zapslog_config_proto_rawDesc), len(file_zapslog_config_proto_rawDesc)))
	})
	return file_zapslog_config_proto_rawDescData
}

var file_zapslog_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_zapslog_config_proto_goTypes = []any{
	(*Log)(nil), // 0: zapslog.Log
}
var file_zapslog_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zapslog_config_proto_init() }
func file_zapslog_config_proto_init() {
	if File_zapslog_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zapslog_config_proto_rawDesc), len(file_zapslog_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zapslog_config_proto_goTypes,
		DependencyIndexes: file_zapslog_config_proto_depIdxs,
		MessageInfos:      file_zapslog_config_proto_msgTypes,
	}.Build()
	File_zapslog_config_proto = out.File
	file_zapslog_config_proto_goTypes = nil
	file_zapslog_config_proto_depIdxs = nil
}
