// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protocol/v1/protocol.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Proto 是 Client 与 Gateway 之间的外部消息封套。
type Proto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            int32                  `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`     // 外部消息类型
	Seq           int32                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`   // 客户端请求响应序号
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"` // 框架处理状态
	Cmd           int32                  `protobuf:"varint,4,opt,name=cmd,proto3" json:"cmd,omitempty"`   // 客户端业务命令
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`  // 客户端业务消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proto) Reset() {
	*x = Proto{}
	mi := &file_protocol_v1_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proto) ProtoMessage() {}

func (x *Proto) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_v1_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proto.ProtoReflect.Descriptor instead.
func (*Proto) Descriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Proto) GetOp() int32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *Proto) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Proto) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Proto) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *Proto) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// ClientAuthReq 只由 Gateway 处理，token 不进入内部 Node RPC。
type ClientAuthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 目标游戏服务
	Token         []byte                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                                // 不透明认证凭据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAuthReq) Reset() {
	*x = ClientAuthReq{}
	mi := &file_protocol_v1_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuthReq) ProtoMessage() {}

func (x *ClientAuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_v1_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuthReq.ProtoReflect.Descriptor instead.
func (*ClientAuthReq) Descriptor() ([]byte, []int) {
	return file_protocol_v1_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *ClientAuthReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ClientAuthReq) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

var File_protocol_v1_protocol_proto protoreflect.FileDescriptor

const file_protocol_v1_protocol_proto_rawDesc = "" +
	"\n" +
	"\x1aprotocol/v1/protocol.proto\x12\vprotocol.v1\"c\n" +
	"\x05Proto\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\x05R\x02op\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x05R\x03seq\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12\x10\n" +
	"\x03cmd\x18\x04 \x01(\x05R\x03cmd\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\"H\n" +
	"\rClientAuthReq\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05token\x18\x02 \x01(\fR\x05tokenB\x19Z\x17yola/api/protocol/v1;v1b\x06proto3"

var (
	file_protocol_v1_protocol_proto_rawDescOnce sync.Once
	file_protocol_v1_protocol_proto_rawDescData []byte
)

func file_protocol_v1_protocol_proto_rawDescGZIP() []byte {
	file_protocol_v1_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_v1_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_v1_protocol_proto_rawDesc), len(file_protocol_v1_protocol_proto_rawDesc)))
	})
	return file_protocol_v1_protocol_proto_rawDescData
}

var file_protocol_v1_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocol_v1_protocol_proto_goTypes = []any{
	(*Proto)(nil),         // 0: protocol.v1.Proto
	(*ClientAuthReq)(nil), // 1: protocol.v1.ClientAuthReq
}
var file_protocol_v1_protocol_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_v1_protocol_proto_init() }
func file_protocol_v1_protocol_proto_init() {
	if File_protocol_v1_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_v1_protocol_proto_rawDesc), len(file_protocol_v1_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_v1_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_v1_protocol_proto_depIdxs,
		MessageInfos:      file_protocol_v1_protocol_proto_msgTypes,
	}.Build()
	File_protocol_v1_protocol_proto = out.File
	file_protocol_v1_protocol_proto_goTypes = nil
	file_protocol_v1_protocol_proto_depIdxs = nil
}
