// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cluster/v1/cluster.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GateRoute 是当前请求携带的不可变 Gateway 连接路由。
type GateRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`    // 目标游戏服务
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`                                       // 稳定用户身份
	BindingToken  string                 `protobuf:"bytes,3,opt,name=binding_token,json=bindingToken,proto3" json:"binding_token,omitempty"` // 当前连接 binding 的 fencing token
	GateId        string                 `protobuf:"bytes,4,opt,name=gate_id,json=gateId,proto3" json:"gate_id,omitempty"`                   // 持有连接的 Gateway 实例
	GateEndpoint  string                 `protobuf:"bytes,5,opt,name=gate_endpoint,json=gateEndpoint,proto3" json:"gate_endpoint,omitempty"` // Gateway 内部 gRPC 地址
	ConnId        string                 `protobuf:"bytes,6,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`                   // Gateway 内的连接标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateRoute) Reset() {
	*x = GateRoute{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateRoute) ProtoMessage() {}

func (x *GateRoute) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateRoute.ProtoReflect.Descriptor instead.
func (*GateRoute) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *GateRoute) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GateRoute) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GateRoute) GetBindingToken() string {
	if x != nil {
		return x.BindingToken
	}
	return ""
}

func (x *GateRoute) GetGateId() string {
	if x != nil {
		return x.GateId
	}
	return ""
}

func (x *GateRoute) GetGateEndpoint() string {
	if x != nil {
		return x.GateEndpoint
	}
	return ""
}

func (x *GateRoute) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

type ForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *GateRoute             `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`                          // 当前请求的 Gateway 连接路由
	Command       int32                  `protobuf:"varint,2,opt,name=command,proto3" json:"command,omitempty"`                     // Node 业务命令
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                            // Node 业务请求
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`          // Stateful 请求期望的 Node 实例；空值表示普通负载均衡
	NodeEpoch     string                 `protobuf:"bytes,5,opt,name=node_epoch,json=nodeEpoch,proto3" json:"node_epoch,omitempty"` // sticky Node 进程代次
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardRequest) GetRoute() *GateRoute {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *ForwardRequest) GetCommand() int32 {
	if x != nil {
		return x.Command
	}
	return 0
}

func (x *ForwardRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ForwardRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ForwardRequest) GetNodeEpoch() string {
	if x != nil {
		return x.NodeEpoch
	}
	return ""
}

type ForwardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"` // 业务响应；错误使用 gRPC status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardReply) Reset() {
	*x = ForwardReply{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardReply) ProtoMessage() {}

func (x *ForwardReply) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardReply.ProtoReflect.Descriptor instead.
func (*ForwardReply) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *ForwardReply) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *GateRoute             `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"` // 断开时的 Gateway 连接路由
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *DisconnectRequest) GetRoute() *GateRoute {
	if x != nil {
		return x.Route
	}
	return nil
}

type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *GateRoute             `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`      // 目标 Gateway 连接
	Command       int32                  `protobuf:"varint,2,opt,name=command,proto3" json:"command,omitempty"` // 客户端业务命令
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`        // 客户端业务消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *PushRequest) GetRoute() *GateRoute {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *PushRequest) GetCommand() int32 {
	if x != nil {
		return x.Command
	}
	return 0
}

func (x *PushRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type KickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *GateRoute             `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"` // 目标 Gateway 连接
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`  // 踢线原因码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickRequest) Reset() {
	*x = KickRequest{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickRequest) ProtoMessage() {}

func (x *KickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickRequest.ProtoReflect.Descriptor instead.
func (*KickRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *KickRequest) GetRoute() *GateRoute {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *KickRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_cluster_v1_cluster_proto protoreflect.FileDescriptor

const file_cluster_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\x18cluster/v1/cluster.proto\x12\n" +
	"cluster.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xbc\x01\n" +
	"\tGateRoute\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12#\n" +
	"\rbinding_token\x18\x03 \x01(\tR\fbindingToken\x12\x17\n" +
	"\agate_id\x18\x04 \x01(\tR\x06gateId\x12#\n" +
	"\rgate_endpoint\x18\x05 \x01(\tR\fgateEndpoint\x12\x17\n" +
	"\aconn_id\x18\x06 \x01(\tR\x06connId\"\xa3\x01\n" +
	"\x0eForwardRequest\x12+\n" +
	"\x05route\x18\x01 \x01(\v2\x15.cluster.v1.GateRouteR\x05route\x12\x18\n" +
	"\acommand\x18\x02 \x01(\x05R\acommand\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"node_epoch\x18\x05 \x01(\tR\tnodeEpoch\"\"\n" +
	"\fForwardReply\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\"@\n" +
	"\x11DisconnectRequest\x12+\n" +
	"\x05route\x18\x01 \x01(\v2\x15.cluster.v1.GateRouteR\x05route\"h\n" +
	"\vPushRequest\x12+\n" +
	"\x05route\x18\x01 \x01(\v2\x15.cluster.v1.GateRouteR\x05route\x12\x18\n" +
	"\acommand\x18\x02 \x01(\x05R\acommand\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"N\n" +
	"\vKickRequest\x12+\n" +
	"\x05route\x18\x01 \x01(\v2\x15.cluster.v1.GateRouteR\x05route\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code2\x8c\x01\n" +
	"\x04Node\x12?\n" +
	"\aForward\x12\x1a.cluster.v1.ForwardRequest\x1a\x18.cluster.v1.ForwardReply\x12C\n" +
	"\n" +
	"Disconnect\x12\x1d.cluster.v1.DisconnectRequest\x1a\x16.google.protobuf.Empty2{\n" +
	"\aGateway\x127\n" +
	"\x04Push\x12\x17.cluster.v1.PushRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x04Kick\x12\x17.cluster.v1.KickRequest\x1a\x16.google.protobuf.EmptyB\x18Z\x16yola/api/cluster/v1;v1b\x06proto3"

var (
	file_cluster_v1_cluster_proto_rawDescOnce sync.Once
	file_cluster_v1_cluster_proto_rawDescData []byte
)

func file_cluster_v1_cluster_proto_rawDescGZIP() []byte {
	file_cluster_v1_cluster_proto_rawDescOnce.Do(func() {
		file_cluster_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_v1_cluster_proto_rawDesc), len(file_cluster_v1_cluster_proto_rawDesc)))
	})
	return file_cluster_v1_cluster_proto_rawDescData
}

var file_cluster_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cluster_v1_cluster_proto_goTypes = []any{
	(*GateRoute)(nil),         // 0: cluster.v1.GateRoute
	(*ForwardRequest)(nil),    // 1: cluster.v1.ForwardRequest
	(*ForwardReply)(nil),      // 2: cluster.v1.ForwardReply
	(*DisconnectRequest)(nil), // 3: cluster.v1.DisconnectRequest
	(*PushRequest)(nil),       // 4: cluster.v1.PushRequest
	(*KickRequest)(nil),       // 5: cluster.v1.KickRequest
	(*emptypb.Empty)(nil),     // 6: google.protobuf.Empty
}
var file_cluster_v1_cluster_proto_depIdxs = []int32{
	0, // 0: cluster.v1.ForwardRequest.route:type_name -> cluster.v1.GateRoute
	0, // 1: cluster.v1.DisconnectRequest.route:type_name -> cluster.v1.GateRoute
	0, // 2: cluster.v1.PushRequest.route:type_name -> cluster.v1.GateRoute
	0, // 3: cluster.v1.KickRequest.route:type_name -> cluster.v1.GateRoute
	1, // 4: cluster.v1.Node.Forward:input_type -> cluster.v1.ForwardRequest
	3, // 5: cluster.v1.Node.Disconnect:input_type -> cluster.v1.DisconnectRequest
	4, // 6: cluster.v1.Gateway.Push:input_type -> cluster.v1.PushRequest
	5, // 7: cluster.v1.Gateway.Kick:input_type -> cluster.v1.KickRequest
	2, // 8: cluster.v1.Node.Forward:output_type -> cluster.v1.ForwardReply
	6, // 9: cluster.v1.Node.Disconnect:output_type -> google.protobuf.Empty
	6, // 10: cluster.v1.Gateway.Push:output_type -> google.protobuf.Empty
	6, // 11: cluster.v1.Gateway.Kick:output_type -> google.protobuf.Empty
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cluster_v1_cluster_proto_init() }
func file_cluster_v1_cluster_proto_init() {
	if File_cluster_v1_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_v1_cluster_proto_rawDesc), len(file_cluster_v1_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_cluster_v1_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_v1_cluster_proto_depIdxs,
		MessageInfos:      file_cluster_v1_cluster_proto_msgTypes,
	}.Build()
	File_cluster_v1_cluster_proto = out.File
	file_cluster_v1_cluster_proto_goTypes = nil
	file_cluster_v1_cluster_proto_depIdxs = nil
}
