// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conf/conf.proto

package conf

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	zapslog "yola/test/internal/zapslog"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Log           *zapslog.Log           `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	Room          *Room                  `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetLog() *zapslog.Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *Bootstrap) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grpc          *Server_GRPC           `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redis         *Data_Redis            `protobuf:"bytes,1,opt,name=redis,proto3" json:"redis,omitempty"`
	Registry      *Data_Registry         `protobuf:"bytes,2,opt,name=registry,proto3" json:"registry,omitempty"`
	AdvertiseHost string                 `protobuf:"bytes,3,opt,name=advertise_host,json=advertiseHost,proto3" json:"advertise_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetRegistry() *Data_Registry {
	if x != nil {
		return x.Registry
	}
	return nil
}

func (x *Data) GetAdvertiseHost() string {
	if x != nil {
		return x.AdvertiseHost
	}
	return ""
}

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *Room_Table            `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Game          *Room_Game             `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	Robot         *Room_Robot            `protobuf:"bytes,3,opt,name=robot,proto3" json:"robot,omitempty"`
	LogCache      *Room_LogCache         `protobuf:"bytes,4,opt,name=logCache,proto3" json:"logCache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Room) GetTable() *Room_Table {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *Room) GetGame() *Room_Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *Room) GetRobot() *Room_Robot {
	if x != nil {
		return x.Robot
	}
	return nil
}

func (x *Room) GetLogCache() *Room_LogCache {
	if x != nil {
		return x.LogCache
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Db            int32                  `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

type Data_Registry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []string               `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	DialTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=dial_timeout,json=dialTimeout,proto3" json:"dial_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Registry) Reset() {
	*x = Data_Registry{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Registry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Registry) ProtoMessage() {}

func (x *Data_Registry) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Registry.ProtoReflect.Descriptor instead.
func (*Data_Registry) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Registry) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Data_Registry) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Data_Registry) GetDialTimeout() *durationpb.Duration {
	if x != nil {
		return x.DialTimeout
	}
	return nil
}

type Room_Table struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableNum      int32                  `protobuf:"varint,1,opt,name=tableNum,proto3" json:"tableNum,omitempty"`
	ChairNum      int32                  `protobuf:"varint,2,opt,name=chairNum,proto3" json:"chairNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room_Table) Reset() {
	*x = Room_Table{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room_Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room_Table) ProtoMessage() {}

func (x *Room_Table) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room_Table.ProtoReflect.Descriptor instead.
func (*Room_Table) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Room_Table) GetTableNum() int32 {
	if x != nil {
		return x.TableNum
	}
	return 0
}

func (x *Room_Table) GetChairNum() int32 {
	if x != nil {
		return x.ChairNum
	}
	return 0
}

type Room_Game struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Vid              int32                  `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"`
	SeeRound         int32                  `protobuf:"varint,2,opt,name=see_round,json=seeRound,proto3" json:"see_round,omitempty"`
	AutoSeeRound     int32                  `protobuf:"varint,3,opt,name=auto_see_round,json=autoSeeRound,proto3" json:"auto_see_round,omitempty"`
	SpeakerCardType  int32                  `protobuf:"varint,4,opt,name=speaker_card_type,json=speakerCardType,proto3" json:"speaker_card_type,omitempty"`
	HighStrengthRate int32                  `protobuf:"varint,5,opt,name=high_strength_rate,json=highStrengthRate,proto3" json:"high_strength_rate,omitempty"`
	IsNewbie         bool                   `protobuf:"varint,6,opt,name=is_newbie,json=isNewbie,proto3" json:"is_newbie,omitempty"`
	AutoReady        bool                   `protobuf:"varint,7,opt,name=auto_ready,json=autoReady,proto3" json:"auto_ready,omitempty"`
	MinMoney         float64                `protobuf:"fixed64,8,opt,name=min_money,json=minMoney,proto3" json:"min_money,omitempty"`
	MaxMoney         float64                `protobuf:"fixed64,9,opt,name=max_money,json=maxMoney,proto3" json:"max_money,omitempty"`
	BaseMoney        float64                `protobuf:"fixed64,10,opt,name=base_money,json=baseMoney,proto3" json:"base_money,omitempty"`
	ChLimit          float64                `protobuf:"fixed64,11,opt,name=ch_limit,json=chLimit,proto3" json:"ch_limit,omitempty"`
	PotLimit         float64                `protobuf:"fixed64,12,opt,name=pot_limit,json=potLimit,proto3" json:"pot_limit,omitempty"`
	Fee              float64                `protobuf:"fixed64,13,opt,name=fee,proto3" json:"fee,omitempty"`
	SpeakerMinmoney  float64                `protobuf:"fixed64,14,opt,name=speaker_minmoney,json=speakerMinmoney,proto3" json:"speaker_minmoney,omitempty"`
	VipLimit         int32                  `protobuf:"varint,15,opt,name=vip_limit,json=vipLimit,proto3" json:"vip_limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Room_Game) Reset() {
	*x = Room_Game{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room_Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room_Game) ProtoMessage() {}

func (x *Room_Game) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room_Game.ProtoReflect.Descriptor instead.
func (*Room_Game) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Room_Game) GetVid() int32 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *Room_Game) GetSeeRound() int32 {
	if x != nil {
		return x.SeeRound
	}
	return 0
}

func (x *Room_Game) GetAutoSeeRound() int32 {
	if x != nil {
		return x.AutoSeeRound
	}
	return 0
}

func (x *Room_Game) GetSpeakerCardType() int32 {
	if x != nil {
		return x.SpeakerCardType
	}
	return 0
}

func (x *Room_Game) GetHighStrengthRate() int32 {
	if x != nil {
		return x.HighStrengthRate
	}
	return 0
}

func (x *Room_Game) GetIsNewbie() bool {
	if x != nil {
		return x.IsNewbie
	}
	return false
}

func (x *Room_Game) GetAutoReady() bool {
	if x != nil {
		return x.AutoReady
	}
	return false
}

func (x *Room_Game) GetMinMoney() float64 {
	if x != nil {
		return x.MinMoney
	}
	return 0
}

func (x *Room_Game) GetMaxMoney() float64 {
	if x != nil {
		return x.MaxMoney
	}
	return 0
}

func (x *Room_Game) GetBaseMoney() float64 {
	if x != nil {
		return x.BaseMoney
	}
	return 0
}

func (x *Room_Game) GetChLimit() float64 {
	if x != nil {
		return x.ChLimit
	}
	return 0
}

func (x *Room_Game) GetPotLimit() float64 {
	if x != nil {
		return x.PotLimit
	}
	return 0
}

func (x *Room_Game) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Room_Game) GetSpeakerMinmoney() float64 {
	if x != nil {
		return x.SpeakerMinmoney
	}
	return 0
}

func (x *Room_Game) GetVipLimit() int32 {
	if x != nil {
		return x.VipLimit
	}
	return 0
}

// 机器人配置
type Room_Robot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Open          bool                   `protobuf:"varint,1,opt,name=open,proto3" json:"open,omitempty"`
	Num           int32                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	TableMaxCount int32                  `protobuf:"varint,3,opt,name=table_max_count,json=tableMaxCount,proto3" json:"table_max_count,omitempty"`
	MinPlayCount  int32                  `protobuf:"varint,4,opt,name=min_play_count,json=minPlayCount,proto3" json:"min_play_count,omitempty"` // 预留N个AI自己玩游戏
	IdBegin       int64                  `protobuf:"varint,5,opt,name=id_begin,json=idBegin,proto3" json:"id_begin,omitempty"`
	MinMoney      float64                `protobuf:"fixed64,6,opt,name=min_money,json=minMoney,proto3" json:"min_money,omitempty"`
	MaxMoney      float64                `protobuf:"fixed64,7,opt,name=max_money,json=maxMoney,proto3" json:"max_money,omitempty"`
	StandMinMoney float64                `protobuf:"fixed64,8,opt,name=stand_min_money,json=standMinMoney,proto3" json:"stand_min_money,omitempty"`
	StandMaxMoney float64                `protobuf:"fixed64,9,opt,name=stand_max_money,json=standMaxMoney,proto3" json:"stand_max_money,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room_Robot) Reset() {
	*x = Room_Robot{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room_Robot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room_Robot) ProtoMessage() {}

func (x *Room_Robot) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room_Robot.ProtoReflect.Descriptor instead.
func (*Room_Robot) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 2}
}

func (x *Room_Robot) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *Room_Robot) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Room_Robot) GetTableMaxCount() int32 {
	if x != nil {
		return x.TableMaxCount
	}
	return 0
}

func (x *Room_Robot) GetMinPlayCount() int32 {
	if x != nil {
		return x.MinPlayCount
	}
	return 0
}

func (x *Room_Robot) GetIdBegin() int64 {
	if x != nil {
		return x.IdBegin
	}
	return 0
}

func (x *Room_Robot) GetMinMoney() float64 {
	if x != nil {
		return x.MinMoney
	}
	return 0
}

func (x *Room_Robot) GetMaxMoney() float64 {
	if x != nil {
		return x.MaxMoney
	}
	return 0
}

func (x *Room_Robot) GetStandMinMoney() float64 {
	if x != nil {
		return x.StandMinMoney
	}
	return 0
}

func (x *Room_Robot) GetStandMaxMoney() float64 {
	if x != nil {
		return x.StandMaxMoney
	}
	return 0
}

type Room_LogCache struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Open          bool                   `protobuf:"varint,1,opt,name=open,proto3" json:"open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room_LogCache) Reset() {
	*x = Room_LogCache{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room_LogCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room_LogCache) ProtoMessage() {}

func (x *Room_LogCache) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room_LogCache.ProtoReflect.Descriptor instead.
func (*Room_LogCache) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 3}
}

func (x *Room_LogCache) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\x1a\x17validate/validate.proto\x1a\x14zapslog/config.proto\"\xcb\x01\n" +
	"\tBootstrap\x124\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06server\x12.\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x04data\x12(\n" +
	"\x03log\x18\x03 \x01(\v2\f.zapslog.LogB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x03log\x12.\n" +
	"\x04room\x18\x04 \x01(\v2\x10.kratos.api.RoomB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x04room\"\xaa\x01\n" +
	"\x06Server\x125\n" +
	"\x04grpc\x18\x01 \x01(\v2\x17.kratos.api.Server.GRPCB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x04grpc\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xef\x02\n" +
	"\x04Data\x126\n" +
	"\x05redis\x18\x01 \x01(\v2\x16.kratos.api.Data.RedisB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05redis\x12?\n" +
	"\bregistry\x18\x02 \x01(\v2\x19.kratos.api.Data.RegistryB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bregistry\x12%\n" +
	"\x0eadvertise_host\x18\x03 \x01(\tR\radvertiseHost\x1aG\n" +
	"\x05Redis\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02db\x1a~\n" +
	"\bRegistry\x12\x1c\n" +
	"\tendpoints\x18\x01 \x03(\tR\tendpoints\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12<\n" +
	"\fdial_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vdialTimeout\"\x82\t\n" +
	"\x04Room\x126\n" +
	"\x05table\x18\x01 \x01(\v2\x16.kratos.api.Room.TableB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05table\x123\n" +
	"\x04game\x18\x02 \x01(\v2\x15.kratos.api.Room.GameB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x04game\x126\n" +
	"\x05robot\x18\x03 \x01(\v2\x16.kratos.api.Room.RobotB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05robot\x125\n" +
	"\blogCache\x18\x04 \x01(\v2\x19.kratos.api.Room.LogCacheR\blogCache\x1aS\n" +
	"\x05Table\x12#\n" +
	"\btableNum\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\btableNum\x12%\n" +
	"\bchairNum\x18\x02 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x04 \x00R\bchairNum\x1a\x85\x04\n" +
	"\x04Game\x12\x10\n" +
	"\x03vid\x18\x01 \x01(\x05R\x03vid\x12\x1b\n" +
	"\tsee_round\x18\x02 \x01(\x05R\bseeRound\x12$\n" +
	"\x0eauto_see_round\x18\x03 \x01(\x05R\fautoSeeRound\x12*\n" +
	"\x11speaker_card_type\x18\x04 \x01(\x05R\x0fspeakerCardType\x12,\n" +
	"\x12high_strength_rate\x18\x05 \x01(\x05R\x10highStrengthRate\x12\x1b\n" +
	"\tis_newbie\x18\x06 \x01(\bR\bisNewbie\x12\x1d\n" +
	"\n" +
	"auto_ready\x18\a \x01(\bR\tautoReady\x12\x1b\n" +
	"\tmin_money\x18\b \x01(\x01R\bminMoney\x12\x1b\n" +
	"\tmax_money\x18\t \x01(\x01R\bmaxMoney\x12-\n" +
	"\n" +
	"base_money\x18\n" +
	" \x01(\x01B\x0e\xfaB\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\tbaseMoney\x12\x19\n" +
	"\bch_limit\x18\v \x01(\x01R\achLimit\x12\x1b\n" +
	"\tpot_limit\x18\f \x01(\x01R\bpotLimit\x12)\n" +
	"\x03fee\x18\r \x01(\x01B\x17\xfaB\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\xf0?)\x00\x00\x00\x00\x00\x00\x00\x00R\x03fee\x12)\n" +
	"\x10speaker_minmoney\x18\x0e \x01(\x01R\x0fspeakerMinmoney\x12\x1b\n" +
	"\tvip_limit\x18\x0f \x01(\x05R\bvipLimit\x1a\xa0\x02\n" +
	"\x05Robot\x12\x12\n" +
	"\x04open\x18\x01 \x01(\bR\x04open\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x05R\x03num\x12&\n" +
	"\x0ftable_max_count\x18\x03 \x01(\x05R\rtableMaxCount\x12$\n" +
	"\x0emin_play_count\x18\x04 \x01(\x05R\fminPlayCount\x12\x19\n" +
	"\bid_begin\x18\x05 \x01(\x03R\aidBegin\x12\x1b\n" +
	"\tmin_money\x18\x06 \x01(\x01R\bminMoney\x12\x1b\n" +
	"\tmax_money\x18\a \x01(\x01R\bmaxMoney\x12&\n" +
	"\x0fstand_min_money\x18\b \x01(\x01R\rstandMinMoney\x12&\n" +
	"\x0fstand_max_money\x18\t \x01(\x01R\rstandMaxMoney\x1a\x1e\n" +
	"\bLogCache\x12\x12\n" +
	"\x04open\x18\x01 \x01(\bR\x04openB#Z!yola/test/ludo/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.api.Bootstrap
	(*Server)(nil),              // 1: kratos.api.Server
	(*Data)(nil),                // 2: kratos.api.Data
	(*Room)(nil),                // 3: kratos.api.Room
	(*Server_GRPC)(nil),         // 4: kratos.api.Server.GRPC
	(*Data_Redis)(nil),          // 5: kratos.api.Data.Redis
	(*Data_Registry)(nil),       // 6: kratos.api.Data.Registry
	(*Room_Table)(nil),          // 7: kratos.api.Room.Table
	(*Room_Game)(nil),           // 8: kratos.api.Room.Game
	(*Room_Robot)(nil),          // 9: kratos.api.Room.Robot
	(*Room_LogCache)(nil),       // 10: kratos.api.Room.LogCache
	(*zapslog.Log)(nil),         // 11: zapslog.Log
	(*durationpb.Duration)(nil), // 12: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	11, // 2: kratos.api.Bootstrap.log:type_name -> zapslog.Log
	3,  // 3: kratos.api.Bootstrap.room:type_name -> kratos.api.Room
	4,  // 4: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	5,  // 5: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	6,  // 6: kratos.api.Data.registry:type_name -> kratos.api.Data.Registry
	7,  // 7: kratos.api.Room.table:type_name -> kratos.api.Room.Table
	8,  // 8: kratos.api.Room.game:type_name -> kratos.api.Room.Game
	9,  // 9: kratos.api.Room.robot:type_name -> kratos.api.Room.Robot
	10, // 10: kratos.api.Room.logCache:type_name -> kratos.api.Room.LogCache
	12, // 11: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	12, // 12: kratos.api.Data.Registry.dial_timeout:type_name -> google.protobuf.Duration
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
