// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"log/slog"
	"yola/test/whot/internal/biz"
	"yola/test/whot/internal/conf"
	"yola/test/whot/internal/data"
	"yola/test/whot/internal/server"
	"yola/test/whot/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(instanceID string, serverConfig *conf.Server, dataConfig *conf.Data, room *conf.Room, logger *slog.Logger) (*kratos.App, func(), error) {
	universalClient, cleanup, err := data.NewRedisClient(dataConfig)
	if err != nil {
		return nil, nil, err
	}
	dataData := data.NewData(universalClient)
	playerRepo := data.NewPlayerRepo(dataData)
	usecase, cleanup2, err := biz.NewUsecase(playerRepo, room)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	serviceService := service.NewService(usecase)
	nodeServer, err := server.NewNodeServer(universalClient, serviceService, serverConfig, dataConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	registry, cleanup3, err := data.NewRegistry(dataConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app, cleanup4 := newApp(instanceID, logger, nodeServer, registry)
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
